### ISSUE TITLE
Nodes tainted with "uninitialized" and never get pods scheduled on them

### ISSUE THREAD

**Issue by asoltesz** [asoltesz/hetzner-k8s-builder#1]
After the Terraform script succeeds, the cluster is available in Rancher but all of the nodes have this taint:

node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule

This results is that workloads get deployed.

Consistently happens (3 cluster creations with different virtual machine sizes)

**Comment by asoltesz** [comment]
It may be that Rancher RKE simply fails with certain installation features on the nodes which is why it leaves this taint on them.

[The events I captured](https://drive.google.com/file/d/12g91a0RVnmnaxgchmdbAnzPAeBgPK4j0/view?usp=sharing) from the Rancher UI after the cluster installation has finished.

There are several errors on it.

@vitobotta
What version of Rancher, Terraform and Ansible are you using?

**Comment by asoltesz** [comment]
After a full Rancher reinstall and cluster-deployment from scratch, I don't have the taint anymore.

Instead of the taint, I now have the "csi.hetzner.cloud/location=nbg1" label which seems to indicate that the Hetzner Cloud Controller Manager has replaced he taint with the location/datacenter tag (the expected behaviour).

I had the taint Terraform finished but it got removed after the Hetzner features got deployed into the cluster.

Either I had some problem in my environment or the cluster installation process is somehow unreliable. 

I will do some further cluster deployments to see if this comes back.

Another difference from earlier attempts that I didn't install the Hetzner Node Driver into my Rancher instance. I have no idea if that could interfere with RKE's cluster creation (by some hooks) or it is only a UI thing for manual/UI cluster creation.

**Comment by vitobotta** [comment]
Yeah that label means it's working as expected. I'm using Rancher 2.3.2 and I think Terraform 0.12.12 if I remember correctly. However (this may surprise you after my blog post) I am now using the node driver. It makes some things easier.

The node driver is only a UI thing and doesn't interfere with RKE etc.

**Comment by asoltesz** [comment]
On subsequent cluster creations, this taint is not present anymore.
