### ISSUE TITLE
Ingresses are stuck in "Initializing" phase, never get "Active"

### ISSUE THREAD

**Issue by asoltesz** [asoltesz/hetzner-k8s-builder#2]
This may be a Rancher issue but after the default RKE cluster installation, none of the newly created Ingresses will ever go to Active status.

Workaround is:
- Cluster >> Edit
- Disable Ingress
- Save
- Cluster >> Edit
- Enable Ingress
- Save

After this, Ingresses seem to deploy properly.

**Comment by asoltesz** [comment]
Seems like this is a known Rancher problem and it is still cropping up: 
- rancher/rancher#16172

**Comment by vitobotta** [comment]
I have the same problem with Traefik controller.

**Comment by asoltesz** [comment]
This turns out to be a problem on our side.

The Rancher Terraform provider simply didn't get the necessary configuration to activate the Nginx-Ingress controller at cluster provisioning time.

After defining the necessary variables and supplying them to the necessary plugin, the issue seems to be gone.
